---
- name: Download and Extract Keycloak Server
  unarchive:
     src: https://downloads.jboss.org/keycloak/6.0.1/keycloak-6.0.1.tar.gz
     dest: /opt
     remote_src: yes

- name: Copy files from keycloak-6.0.1 to keycloak
  copy:
    remote_src: True
    src: /opt/keycloak-6.0.1/.
    dest: /opt/keycloak

- name: Remove file keycloak-6.0.1
  file:
    path: /opt/keycloak-6.0.1
    state: absent

- name: Create group Keycloak
  group:
    name: keycloak
    state: present

- name: Create user Keycloak
  user:
    name: keycloak
    system: yes
    groups: keycloak
    home: /opt/keycloak
    shell: /sbin/nologin
    append: yes

- name: Change file ownership and group for keycloak
  file:
    path: /opt/keycloak
    state: directory
    owner: keycloak
    group: users
    recurse: yes


- name: Change file permissions of bin
  file:
    path: /opt/keycloak/bin
    owner: keycloak
    group: users
    mode: '0751'

- name: Creating a SystemD Service File for Keycloak
  file:
    path: /etc/keycloak
    state: directory
    mode: '0755'

- name: Copy Keycloak configuration file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: preserve
  with_items:
    - { src: /opt/keycloak/docs/contrib/scripts/systemd/wildfly.conf,
        dest: /etc/keycloak/keycloak.conf }
    - { src: /opt/keycloak/docs/contrib/scripts/systemd/launch.sh,
        dest: /opt/keycloak/bin/ }
  become: true

- name: Change file ownership of launch.sh
  file:
    path: /opt/keycloak/bin/launch.sh
    owner: keycloak
    group: keycloak


- name: Update the Keycloak installation path
  replace:
    path: /opt/keycloak/bin/launch.sh
    regexp: 'WILDFLY_HOME=.*$'
    replace: WILDFLY_HOME="/opt/keycloak"

- name: Copy service definition file
  copy:
    src: /opt/keycloak/docs/contrib/scripts/systemd/wildfly.service
    dest: /etc/systemd/system/keycloak.service
    remote_src: yes
    mode: preserve

- name: Configure keycloak.service
  template:
      src: keycloak.service.j2
      dest: /etc/systemd/system/keycloak.service

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes

- name: Start keycloak service
  service:
    name: keycloak
    state: started

- name: Enable keycloak service
  service:
    name: keycloak
    enabled: yes

- name: Run a script to create the initial administrator account
  shell: '/opt/keycloak/bin/add-user-keycloak.sh -r master -u {{ username }} -p {{ password }}'
- name: Enable keycloak service
  service:
    name: keycloak
    enabled: yes
    state: restarted

- name: Start an authenticated session by providing admin user credentials
  shell: '/opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master -u {{ username }} -p {{ password }}'

# - name: Disable SSL on master realm
#   shell: '/opt/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE'
